
atmosphere-grid:
  bottom: 0.0
  top: 1600.0e5
  number-of-layers: 200

photolysis-grid:
  regular-grid: true
  lower-wavelength: 92.5
  upper-wavelength: 855.0
  number-of-bins: 200

planet:
  background-gas: H2
  surface-pressure: 1.000 
  planet-mass: 5.683e29
  planet-radius: 58.232e8 
  surface-albedo: 0.342
  photon-scale-factor: 0.01108
  solar-zenith-angle: 60.0
  hydrogen-escape:
    type: none
  default-gas-lower-boundary: Moses
  water:
    fix-water-in-troposphere: false
    gas-rainout: false
    water-condensation: false

boundary-conditions:
- name: O1D
  type: short lived
- name: N2D
  type: short lived
- name: He
  only-eddy: true
  lower-boundary: {type: mix, mix: 0.0325}
  upper-boundary: {type: veff, veff: 0}
- name: O
  lower-boundary: {type: Moses}
  upper-boundary: {type: flux, flux: -1.5E6}
- name: H2O
  lower-boundary: {type: Moses}
  upper-boundary: {type: flux, flux: -1.5E6}
- name: H
  lower-boundary: {type: Moses}
  upper-boundary: {type: flux, flux: -1.1E9}
- name: CO
  lower-boundary: {type: mix, mix: 1e-9}
  upper-boundary: {type: flux, flux: -3.9E6}
- name: CO2
  lower-boundary: {type: Moses}
  upper-boundary: {type: flux, flux: -7.5E4}
- name: CH4
  lower-boundary: {type: mix, mix: 4.50e-03}
  upper-boundary: {type: veff, veff: 0}


      