
atmosphere-grid:
  bottom: 0.0 # cm
  top: 1600.0e5 # cm
  number-of-layers: 200

photolysis-grid:
  regular-grid: true
  lower-wavelength: 92.5 # nm
  upper-wavelength: 855.0 # nm
  number-of-bins: 200
  photon-scale-factor: 0.01108

planet:
  background-gas: H2
  surface-pressure: 1.000 
  planet-mass: 5.683e29
  planet-radius: 58.232e8 
  surface-albedo: 0.342
  diurnal-averaging-factor: 0.5
  solar-zenith-angle: 50.0
  diff-lim-hydrogen-escape: false
  default-gas-lower-boundary: Moses
  water:
    fix-water-in-troposphere: false
    gas-rainout: false
    water-condensation: true
    condensation-rate: {A: 1.0e-8, rhc: 1, rh0: 1.05}

particles:
- name: H2SO4aer
  condensation-rate: {A: 1.0e-5, rhc: 1.0, rh0: 1.05}
- name: HCNaer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: HCCCNaer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: CH3CNaer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: C2H2aer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: C2H4aer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: C2H6aer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: C4H4aer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: N2Oaer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: NH3aer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}  
    
# Assumes veff = vdep = 0 boundary condition for species not specified.
# Assumes species is long-lived unless specified
boundary-conditions:
- name: O1D
  type: short lived
- name: N2D
  type: short lived
- name: He
  only-eddy: true
  lower-boundary: {type: mix, mix: 0.0325}
  upper-boundary: {type: veff, veff: 0}
- name: O
  lower-boundary: {type: Moses}
  upper-boundary: {type: flux, flux: -1.5E6}
- name: H2O
  lower-boundary: {type: Moses}
  upper-boundary: {type: flux, flux: -1.5E6}
- name: H
  lower-boundary: {type: Moses}
  upper-boundary: {type: flux, flux: -1.1E9}
- name: CO
  lower-boundary: {type: mix, mix: 1e-9}
  upper-boundary: {type: flux, flux: -3.9E6}
- name: CO2
  lower-boundary: {type: Moses}
  upper-boundary: {type: flux, flux: -7.5E4}
- name: CH4
  lower-boundary: {type: mix, mix: 4.50e-03}
  upper-boundary: {type: veff, veff: 0}


      