
atmosphere-grid:
  bottom: 0.0
  top: 1.0e7
  number-of-layers: 200

photolysis-grid:
  regular-grid: true
  lower-wavelength: 92.5
  upper-wavelength: 855.0
  number-of-bins: 200

planet:
  background-gas: CO2
  surface-pressure: 0.0063
  planet-mass: 6.39e26
  planet-radius: 3.3766E8
  surface-albedo: 0.215
  photon-scale-factor: 0.43
  diurnal-averaging-factor: 0.5
  solar-zenith-angle: 60.0
  hydrogen-escape:
    type: diffusion limited
  water:
    fix-water-in-troposphere: false
    # relative-humidity: 0.05
    gas-rainout: false
    tropopause-altitude: 1.5e6
    water-condensation: true
    condensation-rate: {A: 1.0e-05, rhc: 0.01, rh0: 0.0105}

particles:
- name: H2SO4aer
  condensation-rate: {A: 1.0e-05, rhc: 1.0, rh0: 1.05}
- name: HCNaer
  condensation-rate: {A: 1.0e-08, rhc: 1.0, rh0: 1.05}
- name: HCCCNaer
  condensation-rate: {A: 1.0e-08, rhc: 1.0, rh0: 1.05}
- name: CH3CNaer
  condensation-rate: {A: 1.0e-08, rhc: 1.0, rh0: 1.05}
- name: C2H2aer
  condensation-rate: {A: 1.0e-08, rhc: 1.0, rh0: 1.05}
- name: C2H4aer
  condensation-rate: {A: 1.0e-08, rhc: 1.0, rh0: 1.05}
- name: C2H6aer
  condensation-rate: {A: 1.0e-08, rhc: 1.0, rh0: 1.05}
- name: C4H4aer
  condensation-rate: {A: 1.0e-08, rhc: 1.0, rh0: 1.05}
- name: N2Oaer
  condensation-rate: {A: 1.0e-08, rhc: 1.0, rh0: 1.05}
- name: NH3aer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}  

boundary-conditions:
- name: H2O
  lower-boundary: {type: mix, mix: 1e-4}
  upper-boundary: {type: veff, veff: 0.0}
- name: N2
  lower-boundary: {type: mix, mix: 0.026}
  upper-boundary: {type: veff, veff: 0.0}
- name: O2
  lower-boundary: {type: vdep, vdep: 0.0}
  upper-boundary: {type: flux, flux: 5e6}
- name: CO
  lower-boundary: {type: flux, flux: 7.0e6}
  upper-boundary: {type: veff, veff: 0.0}
- name: H2S
  lower-boundary: {type: vdep + dist flux, vdep: 0.02, flux: 1.5e6, height: 20.0}
  upper-boundary: {type: veff, veff: 0.0}
- name: SO2
  lower-boundary: {type: vdep + dist flux, vdep: 0.02, flux: 1.0e7, height: 20.0}
  upper-boundary: {type: veff, veff: 0.0}
- name: S2
  lower-boundary: {type: flux, flux: 2e7}
  upper-boundary: {type: veff, veff: 0.0}
- name: HCl
  lower-boundary: {type: vdep + dist flux, vdep: 0.02, flux: 6.0e6, height: 20.0}
  upper-boundary: {type: veff, veff: 0.0}
- name: O1D
  type: short lived
- name: N2D
  type: short lived
