
atmosphere-grid:
  bottom: 0.0 # cm
  top: 1.0e7 # cm
  number-of-layers: 200

photolysis-grid:
  regular-grid: true
  lower-wavelength: 92.5 # nm
  upper-wavelength: 855.0 # nm
  number-of-bins: 200

planet:
  use-background-gas: true
  background-gas: N2
  surface-pressure: 1.013 # bar
  planet-mass: 5.972e27 # grams
  planet-radius: 6.371e8 # cm. Radius to bottom of atmosphere-grid
  surface-albedo: 0.25 # cm
  diurnal-averaging-factor: 0.5
  solar-zenith-angle: 50.0
  diff-lim-hydrogen-escape: true
  water:
    fix-water-in-troposphere: true
    tropopause-altitude: 1.1e6 # cm
    relative-humidity: manabe
    gas-rainout: true
    stratospheric-condensation: true
    cold-trap-relative-humitity: 0.01 # relative humidity at the cold trap
    condensation-rate: {A: 1.0e-5, rh0: 1.05}
    
particles:
- name: H2SO4aer
  condensation-rate: {A: 1.0e-5, rh0: 1.05}
- name: HCNaer
  condensation-rate: {A: 1.0e-8, rh0: 1.05}
- name: HCCCNaer
  condensation-rate: {A: 1.0e-8, rh0: 1.05}
- name: CH3CNaer
  condensation-rate: {A: 1.0e-8, rh0: 1.05}
- name: C2H2aer
  condensation-rate: {A: 1.0e-8, rh0: 1.05}
- name: C2H4aer
  condensation-rate: {A: 1.0e-8, rh0: 1.05}
- name: C2H6aer
  condensation-rate: {A: 1.0e-8, rh0: 1.05}
- name: C4H4aer
  condensation-rate: {A: 1.0e-8, rh0: 1.05}
- name: N2Oaer
  condensation-rate: {A: 1.0e-8, rh0: 1.05}

# Assumes veff = vdep = 0 boundary condition for species not specified.
# Assumes species is long-lived unless specified
boundary-conditions:
- name: O2
  lower-boundary:
    mix: 0.21
    type: mix
  upper-boundary:
    veff: 0.0
    type: veff
- name: H2
  lower-boundary:
    mix: 5.3E-07
    type: mix
  upper-boundary:
    veff: 0.0
    type: veff
- name: CO2
  lower-boundary:
    mix: 3.6E-4
    type: mix
  upper-boundary:
    veff: 0.0
    type: veff
- name: CH4
  lower-boundary:
    mix: 1.8e-6
    type: mix
  upper-boundary:
    veff: 0.0
    type: veff
- name: CO
  lower-boundary:
    mix: 1.1e-7
    type: mix
  upper-boundary:
    veff: 0.0
    type: veff
- name: N2O
  lower-boundary:
    mix: 3.1e-7
    type: mix
  upper-boundary:
    veff: 0.0
    type: veff
- name: H2SO4aer
  lower-boundary:
    vdep: 1.0e-2
    type: vdep
  upper-boundary:
    veff: 0.0
    type: veff
- name: S8aer
  lower-boundary:
    vdep: 1.0e-2
    type: vdep
  upper-boundary:
    veff: 0.0
    type: veff
- name: HCaer1
  lower-boundary:
    vdep: 1.0e-2
    type: vdep
  upper-boundary:
    veff: 0.0
    type: veff
- name: HCaer2
  lower-boundary:
    vdep: 1.0e-2
    type: vdep
  upper-boundary:
    veff: 0.0
    type: veff
- name: HCaer3
  lower-boundary:
    vdep: 1.0e-2
    type: vdep
  upper-boundary:
    veff: 0.0
    type: veff
- name: O1D
  type: short lived
- name: N2D
  type: short lived

# standard stuff
- name: O
  lower-boundary:
    vdep: 1.0
    type: vdep
  upper-boundary:
    veff: 0.0
    type: veff
- name: H
  lower-boundary:
    vdep: 1.0
    type: vdep
  upper-boundary:
    veff: 0.0
    type: veff
- name: OH
  lower-boundary:
    vdep: 1.0
    type: vdep
  upper-boundary:
    veff: 0.0
    type: veff
- name: HO2
  lower-boundary:
    vdep: 1.0
    type: vdep
  upper-boundary:
    veff: 0.0
    type: veff
- name: H2O2
  lower-boundary:
    vdep: 2.0e-1
    type: vdep
  upper-boundary:
    veff: 0.0
    type: veff
- name: HCO
  lower-boundary:
    vdep: 1.0
    type: vdep
  upper-boundary:
    veff: 0.0
    type: veff
- name: H2CO
  lower-boundary:
    vdep: 2e-1
    type: vdep
  upper-boundary:
    veff: 0.0
    type: veff
- name: CH3
  lower-boundary:
    vdep: 1.0
    type: vdep
  upper-boundary:
    veff: 0.0
    type: veff
- name: NO
  lower-boundary:
    vdep: 3.0e-4
    type: vdep
  upper-boundary:
    veff: 0.0
    type: veff
- name: NO2
  lower-boundary:
    vdep: 3.0e-3
    type: vdep
  upper-boundary:
    veff: 0.0
    type: veff
- name: O3
  lower-boundary:
    vdep: 7.0e-2
    type: vdep
  upper-boundary:
    veff: 0.0
    type: veff
- name: HNO3
  lower-boundary:
    vdep: 2.0e-1
    type: vdep
  upper-boundary:
    veff: 0.0
    type: veff
- name: H2S
  lower-boundary:
    flux: 1.0e8
    vdep: 2.0e-2
    height: 10.0
    type: vdep + dist flux
  upper-boundary:
    veff: 0.0
    type: veff
- name: OCS
  lower-boundary:
    flux: 5.0e7
    vdep: 3.0e-3
    height: 10.0
    type: vdep + dist flux
  upper-boundary:
    veff: 0.0
    type: veff
- name: HSO
  lower-boundary:
    vdep: 1.0
    type: vdep
  upper-boundary:
    veff: 0.0
    type: veff
- name: H2SO4
  lower-boundary:
    vdep: 1.0
    type: vdep
  upper-boundary:
    veff: 0.0
    type: veff
- name: SO2
  lower-boundary:
    flux: 1.0e9
    vdep: 1.0
    height: 10.0
    type: vdep + dist flux
  upper-boundary:
    veff: 0.0
    type: veff
- name: HNCO
  lower-boundary:
    vdep: 1.0
    type: vdep
  upper-boundary:
    veff: 0.0
    type: veff
- name: HCN
  lower-boundary:
    vdep: 7.0e-3
    type: vdep
  upper-boundary:
    veff: 0.0
    type: veff
- name: HCCCN
  lower-boundary:
    vdep: 7.0e-3
    type: vdep
  upper-boundary:
    veff: 0.0
    type: veff
- name: NCO
  lower-boundary:
    vdep: 1.0
    type: vdep
  upper-boundary:
    veff: 0.0
    type: veff
- name: CN
  lower-boundary:
    vdep: 1.0
    type: vdep
  upper-boundary:
    veff: 0.0
    type: veff

      