sudo: required
dist: focal

language: fortran

before_install:
  - sudo apt-get update
  - sudo apt-get install build-essential
  - sudo apt install gfortran-9
  - sudo apt install gcc-9
  - sudo apt install g++-9

install:
  - mkdir build
  - cd build
  - cmake ../
  - make

script:
  - ctest