sudo: required
dist: focal

language: fortran

before_install:
  - sudo apt-get update
  - sudo apt-get install build-essential
  - sudo apt-get install gfortran
  - sudo apt-get install gcc
  - sudo apt-get install g++
  - mkdir build
  - cd build

script:
  - cmake .. -DTRAVIS=ON
  - make
  - ctest

after_success:
  - bash <(curl -s https://codecov.io/bash)