description: Settings for the photochemical model.

atmosphere-grid:
  bottom: 0.0 # cm
  top: 1.0e7 # cm
  number-of-layers: 200

photolysis-grid:
  regular-grid: true
  lower-wavelength: 50.0 # nm
  upper-wavelength: 800.0 # nm
  number-of-bins: 100
  # input-file: my/input/file.txt

planet:
  use-background-gas: true
  background-gas: N2
  surface-pressure: 1.0 # bar
  planet-mass: 5.972e27 # grams
  planet-radius: 6.371e8 # cm. Radius to bottom of atmosphere-grid
  surface-albedo: 0.25 # cm
  diurnal-averaging-factor: 0.5
  solar-zenith-angle: 50.0
  water:
    water-saturated-troposphere: true
    tropopause-altitude: 1.1e6 # cm

# Assumes veff = vdep = 0 boundary condition for species not specified.
# Assumes species is long-lived unless specified
boundary-conditions:
  - name: N
    lower-boundary:
      vdep: 1.0
      type: constant deposition velocity
    upper-boundary:
      veff: 0.0
      type: constant effusion velocity
  - name: CH4
    lower-boundary:
      flux: 1.0e9
      type: constant flux
    upper-boundary:
      veff: 0.0
      type: constant effusion velocity  
  - name: O
    lower-boundary:
      vdep: 1.0
      type: constant deposition velocity
    upper-boundary:
      veff: 0.0
      type: constant effusion velocity
  - name: CO2
    lower-boundary:
      flux: 0.0
      type: constant flux
    upper-boundary:
      veff: 0.0
      type: constant effusion velocity  
  - name: C
    lower-boundary:
      vdep: 1.0
      type: constant deposition velocity
    upper-boundary:
      veff: 1.0
      type: constant effusion velocity
  - name: H2
    lower-boundary:
      vdep: 0.0
      type: constant deposition velocity
    upper-boundary:
      veff: 1.0
      type: constant effusion velocity
  - name: H
    lower-boundary:
      vdep: 0.0
      type: constant deposition velocity
    upper-boundary:
      veff: 1.0
      type: constant effusion velocity
  - name: CO
    lower-boundary:
      vdep: 1.0e-4
      type: constant deposition velocity
    upper-boundary:
      veff: 0.0
      type: constant effusion velocity

