description: Settings for the photochemical model.

atmosphere-grid:
  bottom: 0.0 # cm
  top: 1.0e7 # cm
  number-of-layers: 200

photolysis-grid:
  regular-grid: true
  lower-wavelength: 100.0 # nm
  upper-wavelength: 800.0 # nm
  number-of-bins: 5
  # input-file: my/input/file.txt

planet:
  background-gas: N2
  surface-pressure: 1.0 # bar
  planet-mass: 5.972e27 # grams
  planet-radius: 6.371e8 # cm. Radius to bottom of atmosphere-grid
  surface-albedo: 0.25 # cm
  water:
    water-saturated-troposhere: true
    tropopause-altitude: 1.1e6 # cm

# Assumes veff = vdep = 0 boundary condition for species not specified.
# Assumes species is long-lived unless specified
boundary-conditions:
  - name: H
    type: long lived
    lower-boundary:
      vdep: 0.0
      type: constant deposition velocity
    upper-boundary:
      veff: 0.0
      type: constant effusion velocity

  - name: H2
    lower-boundary:
      vdep: 0.0
      type: constant deposition velocity
    upper-boundary:
      veff: 0.0
      type: constant effusion velocity

  - name: H2O
    lower-boundary:
      vdep: 0.0
      type: constant deposition velocity
    upper-boundary:
      veff: 0.0
      type: constant effusion velocity

  - name: OH
    lower-boundary:
      vdep: 0.0
      type: constant deposition velocity
    upper-boundary:
      veff: 0.0
      type: constant effusion velocity

  - name: O
    lower-boundary:
      vdep: 0.0
      type: constant deposition velocity
    upper-boundary:
      veff: 0.0
      type: constant effusion velocity
