
atmosphere-grid:
  bottom: 0.0
  top: 1500.0e5
  number-of-layers: 200

photolysis-grid:
  regular-grid: true
  lower-wavelength: 92.5 # nm
  upper-wavelength: 855.0 # nm
  number-of-bins: 200
  photon-scale-factor: 0.036982

planet:
  background-gas: H2
  surface-pressure: 6.708
  planet-mass: 1.898e30
  planet-radius: 7.1492e9
  surface-albedo: 0.343
  diurnal-averaging-factor: 0.5
  solar-zenith-angle: 50.0
  hydrogen-escape:
    type: none
  default-gas-lower-boundary: Moses
  water:
    fix-water-in-troposphere: false
    gas-rainout: false
    water-condensation: true
    condensation-rate: {A: 1.0e-8, rhc: 1, rh0: 1.05}

particles:
- name: H2SO4aer
  condensation-rate: {A: 1.0e-5, rhc: 1.0, rh0: 1.05}
- name: HCNaer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: HCCCNaer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: CH3CNaer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: C2H2aer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: C2H4aer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: C2H6aer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: C4H4aer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: N2Oaer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: NH3aer
  condensation-rate: {A: 1.0e-7, rhc: 1.0, rh0: 1.05}

boundary-conditions:
- name: O1D
  type: short lived
- name: N2D
  type: short lived
- name: He
  only-eddy: true
  lower-boundary: {type: mix, mix: 0.136}
  upper-boundary: {type: veff, veff: 0}
- name: CH4
  lower-boundary: {type: mix, mix: 1.81e-03}
  upper-boundary: {type: veff, veff: 0}
- name: CO
  lower-boundary: {type: mix, mix: 8e-10}
  upper-boundary: {type: flux, flux: -1e6}
- name: CO2
  lower-boundary: {type: Moses}
  upper-boundary: {type: flux, flux: -1e4}
- name: H2O
  lower-boundary: {type: Moses}
  upper-boundary: {type: flux, flux: -4e4}
- name: NH3
  lower-boundary: {type: mix, mix: 3e-4}
  upper-boundary: {type: veff, veff: 0}


      