
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/data/cjm267/.conda/envs/photochem_conda/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 5.14.0-503.22.1.el9_5.x86_64 - x86_64
...
