
atmosphere-grid:
  bottom: 0.0 # cm
  top: 1400.0e5 # cm
  number-of-layers: 200

photolysis-grid:
  regular-grid: true
  lower-wavelength: 92.5 # nm
  upper-wavelength: 855.0 # nm
  number-of-bins: 200
  photon-scale-factor: 0.01089

planet:
  use-background-gas: true
  background-gas: N2
  surface-pressure: 1.500 # bar
  planet-mass: 1.345e26 # grams
  planet-radius: 2.575e8 # cm. Radius to bottom of atmosphere-grid
  surface-albedo: 0.1 # cm
  diurnal-averaging-factor: 0.5
  solar-zenith-angle: 50.0
  diff-lim-hydrogen-escape: true
  water:
    fix-water-in-troposphere: false
    gas-rainout: false
    water-condensation: true
    condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}

particles:
- name: H2SO4aer
  condensation-rate: {A: 1.0e-5, rhc: 1.0, rh0: 1.05}
- name: HCNaer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: HCCCNaer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: CH3CNaer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: C2H2aer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: C2H4aer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: C2H6aer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: C4H4aer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: N2Oaer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
      
# Assumes veff = vdep = 0 boundary condition for species not specified.
# Assumes species is long-lived unless specified
boundary-conditions:
- name: CH4
  lower-boundary: {type: mix, mix: 1.5e-2}
  upper-boundary: {type: veff, veff: 0.0}
- name: HCaer1
  lower-boundary: {type: vdep, vdep: 1.0e-2}
  upper-boundary: {type: veff, veff: 0.0}
- name: HCaer2
  lower-boundary: {type: vdep, vdep: 1.0e-2}
  upper-boundary: {type: veff, veff: 0.0}
- name: HCaer3
  lower-boundary: {type: vdep, vdep: 1.0e-2}
  upper-boundary: {type: veff, veff: 0.0}
- name: O1D
  type: short lived
- name: N2D
  type: short lived
  
