
atmosphere-grid:
  bottom: 0.0
  top: 1400.0e5
  number-of-layers: 200

photolysis-grid:
  regular-grid: true
  lower-wavelength: 92.5
  upper-wavelength: 855.0
  number-of-bins: 200

planet:
  background-gas: N2
  surface-pressure: 1.500
  planet-mass: 1.345e26
  planet-radius: 2.575e8
  surface-albedo: 0.1
  photon-scale-factor: 0.01089
  solar-zenith-angle: 60.0
  hydrogen-escape:
    type: diffusion limited
  water:
    fix-water-in-troposphere: false
    gas-rainout: false
    water-condensation: false

boundary-conditions:
- name: CH4
  lower-boundary: {type: mix, mix: 1.5e-2}
  upper-boundary: {type: veff, veff: 0.0}
- name: O1D
  type: short lived
- name: N2D
  type: short lived
  
