description:
  Settings for the photochemical model.

lightning: # turn it on or off
  on-off: true
  NO-production: 1.0e9 # column-integrated NO production rate from lightning
rainout:
  on-off: false
  multiplier: 1.0 # multiplier for rainout rates
grid:
  bottom: 0.0 # cm
  top: 1.0e7 # cm
  number-of-layers: 200
photo-grid:
  regular-grid: true
  lower-wavelength: 100.0 # nm
  upper-wavelength: 800.0 # nm
  number-of-bins: 150
  # filename: "grid.txt" # can specify a grid file if regular-grid: false
gravity: 981.0 # cm/s2
surface-pressure: 1.0 # bar
planet-radius: 6.371e8 # cm
surface-albedo: 0.25 # cm
topopause-altitude: 1.1e6 # cm


species:
  - 1
  - 2
  - 3

