# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BUILD_SOURCE_DIRS "/data/cjm267/photochem;/data/cjm267/photochem/_skbuild/linux-x86_64-3.12/cmake-build")
set(CPACK_CMAKE_GENERATOR "Ninja")
set(CPACK_COMPONENTS_ALL "Development;Unspecified")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "libhdf5-dev (>=1.10)")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/data/cjm267/.conda/envs/photochem/share/cmake-3.31/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "Photochem built using CMake")
set(CPACK_DMG_SLA_USE_RESOURCE_FILE_LICENSE "ON")
set(CPACK_GENERATOR "TZST")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALL_CMAKE_PROJECTS "/data/cjm267/photochem/_skbuild/linux-x86_64-3.12/cmake-build;Photochem;ALL;/")
set(CPACK_INSTALL_PREFIX "/data/cjm267/photochem/_skbuild/linux-x86_64-3.12/cmake-install")
set(CPACK_MODULE_PATH "/data/cjm267/photochem/_skbuild/linux-x86_64-3.12/cmake-build/_deps/h5fortran-src/cmake/Modules")
set(CPACK_NSIS_DISPLAY_NAME "Photochem 0.6.2")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "Photochem 0.6.2")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "/usr/bin/objcopy")
set(CPACK_OBJDUMP_EXECUTABLE "/usr/bin/objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/data/cjm267/photochem/_skbuild/linux-x86_64-3.12/cmake-build/CPackConfig.cmake")
set(CPACK_OUTPUT_FILE_PREFIX "/data/cjm267/photochem/_skbuild/linux-x86_64-3.12/cmake-build/_deps/h5fortran-build/package")
set(CPACK_PACKAGE_CONTACT "Michael Hirsch")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/data/cjm267/.conda/envs/photochem/share/cmake-3.31/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Photochem built using CMake")
set(CPACK_PACKAGE_DIRECTORY "/data/cjm267/photochem/_skbuild/linux-x86_64-3.12/cmake-build/_deps/h5fortran-build")
set(CPACK_PACKAGE_FILE_NAME "Photochem-0.6.2-Linux")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "Photochem 0.6.2")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "Photochem 0.6.2")
set(CPACK_PACKAGE_NAME "Photochem")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Michael Hirsch")
set(CPACK_PACKAGE_VERSION "0.6.2")
set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "6")
set(CPACK_PACKAGE_VERSION_PATCH "2")
set(CPACK_READELF_EXECUTABLE "/usr/bin/readelf")
set(CPACK_RESOURCE_FILE_LICENSE "/data/cjm267/photochem/_skbuild/linux-x86_64-3.12/cmake-build/_deps/h5fortran-src/LICENSE")
set(CPACK_RESOURCE_FILE_README "/data/cjm267/photochem/_skbuild/linux-x86_64-3.12/cmake-build/_deps/h5fortran-src/README.md")
set(CPACK_RESOURCE_FILE_WELCOME "/data/cjm267/.conda/envs/photochem/share/cmake-3.31/Templates/CPack.GenericWelcome.txt")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TZST")
set(CPACK_SOURCE_IGNORE_FILES "\\.git/;\\.git*;\\.vscode/;\\.mypy_cache/;;_CPack_Packages/;build*/;paper/;")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/data/cjm267/photochem/_skbuild/linux-x86_64-3.12/cmake-build/CPackSourceConfig.cmake")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Linux")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/data/cjm267/photochem/_skbuild/linux-x86_64-3.12/cmake-build/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
