description: Settings for the photochemical model.

atmosphere-grid:
  bottom: 0.0 # cm
  top: 1.0e7 # cm
  number-of-layers: 200

photolysis-grid:
  regular-grid: true
  lower-wavelength: 92.5 # nm
  upper-wavelength: 855.0 # nm
  number-of-bins: 200
  # input-file: my/input/file.txt

planet:
  use-background-gas: true
  background-gas: N2
  surface-pressure: 1.013 # bar
  planet-mass: 5.972e27 # grams
  planet-radius: 6.371e8 # cm. Radius to bottom of atmosphere-grid
  surface-albedo: 0.25 # cm
  diurnal-averaging-factor: 0.5
  solar-zenith-angle: 50.0
  diff-lim-hydrogen-escape: true
  water:
    fix-water-in-troposphere: true
    tropopause-altitude: 1.1e6 # cm
    relative-humidity: manabe
    stratospheric-condensation: true
    cold-trap-relative-humitity: 0.1 # relative humidity at the cold trap
    condensation-rate: 
      A: 1.0e-5
      rh0: 1.05

particles:
  - name: H2SO4aer
    condensation-rate:
      A: 1.0e-5
      rh0: 1.05 

# Assumes veff = vdep = 0 boundary condition for species not specified.
# Assumes species is long-lived unless specified
boundary-conditions:
  - name: H2
    lower-boundary:
      mixing-ratio: 1.2e-4
      type: mixing-ratio
    upper-boundary:
      veff: 0.0
      type: effusion velocity
  - name: CO2
    lower-boundary:
      mixing-ratio: 3e-2
      type: mixing-ratio
    upper-boundary:
      veff: 0.0
      type: effusion velocity
  - name: CH4
    lower-boundary:
      mixing-ratio: 1.2e-3
      type: mixing-ratio
    upper-boundary:
      veff: 0.0
      type: effusion velocity
  - name: CO
    lower-boundary:
      mixing-ratio: 2e-4
      type: mixing-ratio
    upper-boundary:
      veff: 0.0
      type: effusion velocity
  - name: O1D
    type: short lived
  - name: 1CH2
    type: short lived
  - name: NNH
    type: short lived
  - name: N2D
    type: short lived
  - name: HCl
    lower-boundary:
      flux: 1.0e6
      type: flux
    upper-boundary:
      veff: 0.0
      type: effusion velocity
  - name: Cl
    lower-boundary:
      vdep: 1.0
      type: deposition velocity
    upper-boundary:
      veff: 0.0
      type: effusion velocity
    
# to get rid of S and H in the model
  # - name: S8
  #   lower-boundary:
  #     vdep: 1.0
  #     type: deposition velocity
  #   upper-boundary:
  #     veff: 0.0
  #     type: effusion velocity
  # - name: S8L
  #   lower-boundary:
  #     vdep: 1.0
  #     type: deposition velocity
  #   upper-boundary:
  #     veff: 0.0
  #     type: effusion velocity
  # - name: S
  #   lower-boundary:
  #     vdep: 1.0
  #     type: deposition velocity
  #   upper-boundary:
  #     veff: 1.0
  #     type: effusion velocity
  # - name: NNH
  #   lower-boundary:
  #     vdep: 1.0
  #     type: deposition velocity
  #   upper-boundary:
  #     veff: 1.0
  #     type: effusion velocity
  # - name: NH
  #   lower-boundary:
  #     vdep: 1.0
  #     type: deposition velocity
  #   upper-boundary:
  #     veff: 1.0
  #     type: effusion velocity

# standard stuff
  - name: O
    lower-boundary:
      vdep: 1.0
      type: deposition velocity
    upper-boundary:
      veff: 0.0
      type: effusion velocity
  - name: H
    lower-boundary:
      vdep: 1.0
      type: deposition velocity
    upper-boundary:
      veff: 0.0
      type: effusion velocity
  - name: OH
    lower-boundary:
      vdep: 1.0
      type: deposition velocity
    upper-boundary:
      veff: 0.0
      type: effusion velocity
  - name: HO2
    lower-boundary:
      vdep: 1.0
      type: deposition velocity
    upper-boundary:
      veff: 0.0
      type: effusion velocity
  - name: H2O2
    lower-boundary:
      vdep: 2.0e-1
      type: deposition velocity
    upper-boundary:
      veff: 0.0
      type: effusion velocity
  - name: HCO
    lower-boundary:
      vdep: 1.0
      type: deposition velocity
    upper-boundary:
      veff: 0.0
      type: effusion velocity
  - name: H2CO
    lower-boundary:
      vdep: 2e-1
      type: deposition velocity
    upper-boundary:
      veff: 0.0
      type: effusion velocity
  - name: CH3
    lower-boundary:
      vdep: 1.0
      type: deposition velocity
    upper-boundary:
      veff: 0.0
      type: effusion velocity
  - name: NO
    lower-boundary:
      vdep: 3.0e-4
      type: deposition velocity
    upper-boundary:
      veff: 0.0
      type: effusion velocity
  - name: NO2
    lower-boundary:
      vdep: 3.0e-3
      type: deposition velocity
    upper-boundary:
      veff: 0.0
      type: effusion velocity
  - name: O3
    lower-boundary:
      vdep: 7.0e-2
      type: deposition velocity
    upper-boundary:
      veff: 0.0
      type: effusion velocity
  - name: HNO3
    lower-boundary:
      vdep: 2.0e-1
      type: deposition velocity
    upper-boundary:
      veff: 0.0
      type: effusion velocity
  - name: H2S
    lower-boundary:
      flux: 3.5e8
      vdep: 2.0e-2
      distributed-height: 10.0
      type: deposition velocity + distributed flux
    upper-boundary:
      veff: 0.0
      type: effusion velocity
  - name: HSO
    lower-boundary:
      vdep: 1.0
      type: deposition velocity
    upper-boundary:
      veff: 0.0
      type: effusion velocity
  - name: H2SO4
    lower-boundary:
      vdep: 1.0
      type: deposition velocity
    upper-boundary:
      veff: 0.0
      type: effusion velocity
  - name: SO2
    lower-boundary:
      flux: 3.5e9
      vdep: 1.0
      distributed-height: 10.0
      type: deposition velocity + distributed flux
    upper-boundary:
      veff: 0.0
      type: effusion velocity
  - name: HNCO
    lower-boundary:
      vdep: 1.0
      type: deposition velocity
    upper-boundary:
      veff: 0.0
      type: effusion velocity
  - name: HCN
    lower-boundary:
      vdep: 7.0e-3
      type: deposition velocity
    upper-boundary:
      veff: 0.0
      type: effusion velocity
  - name: HCCCN
    lower-boundary:
      vdep: 7.0e-3
      type: deposition velocity
    upper-boundary:
      veff: 0.0
      type: effusion velocity
  - name: NCO
    lower-boundary:
      vdep: 1.0
      type: deposition velocity
    upper-boundary:
      veff: 0.0
      type: effusion velocity
  - name: CN
    lower-boundary:
      vdep: 1.0
      type: deposition velocity
    upper-boundary:
      veff: 0.0
      type: effusion velocity

      