name: CMake

on:
  push:
    branches: [ "main", "dev"]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: awvwgk/setup-fortran@main
      id: setup-fortran
      with:
        compiler: gcc
        version: 11

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: configure cmake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: build fortran
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: testrun
      working-directory: ${{github.workspace}}/build
      run: ./testrun

    - name: memtest
      working-directory: ${{github.workspace}}/build
      run: valgrind --error-exitcode=1 --leak-check=full ./memtest

    - name: build python
      run: python -m pip install . -v

    - name: test python
      working-directory: ${{github.workspace}}/test
      run: python test.py