name: test

on: push

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Setup Fortran
      uses: awvwgk/setup-fortran@main
      id: setup-fortran
      with:
        compiler: gcc
        version: 11

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install h5py fypp
        sudo apt-get install valgrind
        sudo apt-get install libhdf5-dev

    - name: configure cmake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: build fortran
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: test fortran
      working-directory: ${{github.workspace}}/build
      run: |
        valgrind --error-exitcode=1 --leak-check=full ./tests/memtest
        valgrind --error-exitcode=1 --leak-check=full ./tests/testevo
        valgrind --error-exitcode=1 --leak-check=full ./tests/memtest_evo

    - name: build python
      run: python -m pip install . -v

    - name: test python
      working-directory: ${{github.workspace}}/tests
      run: python test.py